In [1]:
import sys, os

# assuming this notebook is in the "notebooks" folder
project_root = os.path.abspath("..")  # go up one level

if project_root not in sys.path:
    sys.path.insert(0, project_root)

print("Project root added to sys.path:", project_root)

Project root added to sys.path: /workspaces/schedule-tool

In [2]:
from src.io import load_schedule_input, save_schedule_output
from src.logic import compute_schedule

In [4]:
df_input = load_schedule_input("20251110_TestScheduleTool.xlsx")
df_input.head()

Loading from: /workspaces/schedule-tool/data/raw/20251110_TestScheduleTool.xlsx

,RecipeNumber,ComponentName,Laser,RollForm,SeamWeld,Emboss,Flanger,RobotWeld,FinalInspection
0,1,Tank,6.358333,6,7,7,9,22,72
1,4,Tank,7.166667,6,7,7,9,22,72
2,7,Tank,7.448039,6,7,7,9,22,72

In [9]:
import pandas as pd

file_path = "../data/raw/20251110_TestScheduleTool.xlsx"

df_tank  = pd.read_excel(file_path, sheet_name="RecipeTank")
df_base  = pd.read_excel(file_path, sheet_name="RecipeBase")
df_lid   = pd.read_excel(file_path, sheet_name="RecipeLid")
df_sku   = pd.read_excel(file_path, sheet_name="SKU")
df_sched = pd.read_excel(file_path, sheet_name="Schedule")

df_sku.head()

      SKU  RecipeTank  RecipeLid  RecipeBase
0  Pole19           1          2           3
1  Pole21           4          5           6
2  Pole24           7          8           9

In [12]:
import pandas as pd

file_path = "../data/raw/20251110_TestScheduleTool.xlsx"

df_tank  = pd.read_excel(file_path, sheet_name="RecipeTank", dtype={"RecipeNumber": str})
df_lid   = pd.read_excel(file_path, sheet_name="RecipeLid",  dtype={"RecipeNumber": str})
df_base  = pd.read_excel(file_path, sheet_name="RecipeBase", dtype={"RecipeNumber": str})

# One big recipe table
df_recipes = pd.concat([df_tank, df_lid, df_base], ignore_index=True)
df_recipes["RecipeNumber"] = df_recipes["RecipeNumber"].astype(int).astype(str).str.zfill(3)
df_recipes = df_recipes.sort_values(by="RecipeNumber").reset_index(drop=True)

df_recipes.head()

,RecipeNumber,ComponentName,Laser,RollForm,SeamWeld,Emboss,Flanger,RobotWeld,FinalInspection
0,001,Tank,6.358333,6.0,7.0,7.0,9.0,22.0,72.0
1,002,Lid,7.366667,NaN,NaN,NaN,NaN,NaN,NaN
2,003,Base,6.358333,NaN,NaN,NaN,NaN,NaN,NaN
3,004,Tank,7.166667,6.0,7.0,7.0,9.0,22.0,72.0
4,005,Lid,7.952083,NaN,NaN,NaN,NaN,NaN,NaN